### ISSUE TITLE
Is there a way to simulate tracking:buffered event?

### ISSUE THREAD

**Issue by mayeaux** [spodlecki/videojs-event-tracking#19]
I'm writing some code to handle buffering events. Do you have any suggestion on how to simulate the buffered effect so I can test my integration? Thanks!

**Comment by spodlecki** [comment]
@mayeaux you could write tests -- it is also just html5 video so you could trigger it manually and see if you get the expected results... another option is to use chrome devtools and turn your machine into a DSL Connection with a super large video file... that'll certainly generate some buffering events!

**Comment by mayeaux** [comment]
The best thing I found was to use the keyboard to seek forward a few seconds on the video, somehow that really triggers the buffer event. Thanks!
